#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Nutiteq.AdvancedMap3D.Resource", IsApplication=true)]

namespace Nutiteq.AdvancedMap3D
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int background_plane = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int direction_down = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int direction_up = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int direction_upthenleft = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int direction_upthenright = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int file_picker_back = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int file_picker_file = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int file_picker_folder = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int ic_menu_search = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int Icon = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int monoandroidsplash = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int olmarker = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int point = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int sky_small = 2130837517;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080005
			public const int editableMapView = 2131230725;
			
			// aapt resource value: 0x7f080000
			public const int filePickerView = 2131230720;
			
			// aapt resource value: 0x7f080009
			public const int info_fragment = 2131230729;
			
			// aapt resource value: 0x7f08000b
			public const int info_text = 2131230731;
			
			// aapt resource value: 0x7f08000f
			public const int listViewResults = 2131230735;
			
			// aapt resource value: 0x7f080004
			public const int mainView = 2131230724;
			
			// aapt resource value: 0x7f08000c
			public const int mapView = 2131230732;
			
			// aapt resource value: 0x7f08000a
			public const int map_fragment = 2131230730;
			
			// aapt resource value: 0x7f080013
			public const int maps_group = 2131230739;
			
			// aapt resource value: 0x7f08002a
			public const int menu3d_blom = 2131230762;
			
			// aapt resource value: 0x7f08002d
			public const int menu3d_chicago = 2131230765;
			
			// aapt resource value: 0x7f080028
			public const int menu3d_demo = 2131230760;
			
			// aapt resource value: 0x7f080029
			public const int menu3d_hover = 2131230761;
			
			// aapt resource value: 0x7f08002e
			public const int menu3d_la = 2131230766;
			
			// aapt resource value: 0x7f08002c
			public const int menu3d_seattle = 2131230764;
			
			// aapt resource value: 0x7f08002b
			public const int menu3d_tomtomlod3 = 2131230763;
			
			// aapt resource value: 0x7f080026
			public const int menu_barcelona = 2131230758;
			
			// aapt resource value: 0x7f08001a
			public const int menu_bing = 2131230746;
			
			// aapt resource value: 0x7f08001b
			public const int menu_bingaerial = 2131230747;
			
			// aapt resource value: 0x7f080023
			public const int menu_coburg = 2131230755;
			
			// aapt resource value: 0x7f08001f
			public const int menu_hillshade = 2131230751;
			
			// aapt resource value: 0x7f080015
			public const int menu_mapbox = 2131230741;
			
			// aapt resource value: 0x7f080016
			public const int menu_mapboxretina = 2131230742;
			
			// aapt resource value: 0x7f080017
			public const int menu_mapboxsatellite = 2131230743;
			
			// aapt resource value: 0x7f080018
			public const int menu_mapboxsatelliteretina = 2131230744;
			
			// aapt resource value: 0x7f080021
			public const int menu_marker = 2131230753;
			
			// aapt resource value: 0x7f080020
			public const int menu_nml = 2131230752;
			
			// aapt resource value: 0x7f08001d
			public const int menu_openaerial = 2131230749;
			
			// aapt resource value: 0x7f080014
			public const int menu_openstreetmap = 2131230740;
			
			// aapt resource value: 0x7f080024
			public const int menu_petronas = 2131230756;
			
			// aapt resource value: 0x7f080025
			public const int menu_sf = 2131230757;
			
			// aapt resource value: 0x7f080019
			public const int menu_stamenterrain = 2131230745;
			
			// aapt resource value: 0x7f08001c
			public const int menu_stored = 2131230748;
			
			// aapt resource value: 0x7f080022
			public const int menu_tileborders = 2131230754;
			
			// aapt resource value: 0x7f080027
			public const int menu_tll = 2131230759;
			
			// aapt resource value: 0x7f08001e
			public const int overlay_group = 2131230750;
			
			// aapt resource value: 0x7f08002f
			public const int search = 2131230767;
			
			// aapt resource value: 0x7f080007
			public const int seekBar = 2131230727;
			
			// aapt resource value: 0x7f080003
			public const int sql = 2131230723;
			
			// aapt resource value: 0x7f08000e
			public const int text = 2131230734;
			
			// aapt resource value: 0x7f080001
			public const int text1 = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int text2 = 2131230722;
			
			// aapt resource value: 0x7f080008
			public const int textView = 2131230728;
			
			// aapt resource value: 0x7f08000d
			public const int textViewMessage = 2131230733;
			
			// aapt resource value: 0x7f080011
			public const int txt_appdata = 2131230737;
			
			// aapt resource value: 0x7f080012
			public const int txt_deliveredby = 2131230738;
			
			// aapt resource value: 0x7f080010
			public const int txt_query = 2131230736;
			
			// aapt resource value: 0x7f080006
			public const int zoomcontrols = 2131230726;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int activity_file_picker = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int detailrow = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int dialog_sql = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int editable = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int fragment_info = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int fragment_main = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int info_fragment = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int list = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int Main = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int MainGPS = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int MainSearch = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int search_query_results = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int searchrow = 2130903052;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f070000
			public const int mainmenu = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int online3d = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int options_menu = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int spatialite = 2131165187;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f050000
			public const int definitions = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int milktruck = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int t0_0_0 = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int t1_0_0 = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int t1_0_1 = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int t1_1_0 = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int t1_1_1 = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int t2_0_0 = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int t2_0_1 = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int t2_0_2 = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int t2_0_3 = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int t2_1_0 = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public const int t2_1_1 = 2131034124;
			
			// aapt resource value: 0x7f05000d
			public const int t2_1_2 = 2131034125;
			
			// aapt resource value: 0x7f05000e
			public const int t2_1_3 = 2131034126;
			
			// aapt resource value: 0x7f05000f
			public const int t2_2_0 = 2131034127;
			
			// aapt resource value: 0x7f050010
			public const int t2_2_1 = 2131034128;
			
			// aapt resource value: 0x7f050011
			public const int t2_2_2 = 2131034129;
			
			// aapt resource value: 0x7f050012
			public const int t2_2_3 = 2131034130;
			
			// aapt resource value: 0x7f050013
			public const int t2_3_0 = 2131034131;
			
			// aapt resource value: 0x7f050014
			public const int t2_3_1 = 2131034132;
			
			// aapt resource value: 0x7f050015
			public const int t2_3_2 = 2131034133;
			
			// aapt resource value: 0x7f050016
			public const int t2_3_3 = 2131034134;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060001
			public const int app_name = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int hello = 2131099648;
			
			// aapt resource value: 0x7f060003
			public const int search_hint = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int search_invoke = 2131099652;
			
			// aapt resource value: 0x7f060002
			public const int search_label = 2131099650;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f040000
			public const int searchable = 2130968576;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
	}
}
#pragma warning restore 1591
