#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Columbia583.Android.Resource", IsApplication=true)]

namespace Columbia583.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f05002c
			public const int activities = 2131034156;
			
			// aapt resource value: 0x7f050004
			public const int activityOptions = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int activityOptionsScroll = 2131034115;
			
			// aapt resource value: 0x7f05002f
			public const int amenities = 2131034159;
			
			// aapt resource value: 0x7f050007
			public const int amenityOptions = 2131034119;
			
			// aapt resource value: 0x7f050006
			public const int amenityOptionsScroll = 2131034118;
			
			// aapt resource value: 0x7f050001
			public const int button_searchTrails = 2131034113;
			
			// aapt resource value: 0x7f05001b
			public const int button_updateSearchResults = 2131034139;
			
			// aapt resource value: 0x7f050030
			public const int commentsList = 2131034160;
			
			// aapt resource value: 0x7f050024
			public const int description = 2131034148;
			
			// aapt resource value: 0x7f05002a
			public const int difficultyRating = 2131034154;
			
			// aapt resource value: 0x7f05002e
			public const int directions = 2131034158;
			
			// aapt resource value: 0x7f050020
			public const int distance = 2131034144;
			
			// aapt resource value: 0x7f050021
			public const int duration = 2131034145;
			
			// aapt resource value: 0x7f05001a
			public const int editText_maxDistance = 2131034138;
			
			// aapt resource value: 0x7f050018
			public const int editText_maxDuration = 2131034136;
			
			// aapt resource value: 0x7f05001c
			public const int gridLayout_searchResults = 2131034140;
			
			// aapt resource value: 0x7f05001e
			public const int imageView1 = 2131034142;
			
			// aapt resource value: 0x7f05001d
			public const int layout1 = 2131034141;
			
			// aapt resource value: 0x7f050028
			public const int maintenance = 2131034152;
			
			// aapt resource value: 0x7f050026
			public const int openStatus = 2131034150;
			
			// aapt resource value: 0x7f05000a
			public const int radioButton_difficulty_easiest = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int radioButton_difficulty_easy = 2131034123;
			
			// aapt resource value: 0x7f05000e
			public const int radioButton_difficulty_extremelyDifficult = 2131034126;
			
			// aapt resource value: 0x7f05000c
			public const int radioButton_difficulty_moreDifficult = 2131034124;
			
			// aapt resource value: 0x7f05000d
			public const int radioButton_difficulty_veryDifficult = 2131034125;
			
			// aapt resource value: 0x7f050012
			public const int radioButton_rating_1 = 2131034130;
			
			// aapt resource value: 0x7f050013
			public const int radioButton_rating_2 = 2131034131;
			
			// aapt resource value: 0x7f050014
			public const int radioButton_rating_3 = 2131034132;
			
			// aapt resource value: 0x7f050015
			public const int radioButton_rating_4 = 2131034133;
			
			// aapt resource value: 0x7f050016
			public const int radioButton_rating_5 = 2131034134;
			
			// aapt resource value: 0x7f050009
			public const int radioGroup_difficulties = 2131034121;
			
			// aapt resource value: 0x7f050011
			public const int radioGroup_ratings = 2131034129;
			
			// aapt resource value: 0x7f05001f
			public const int rating = 2131034143;
			
			// aapt resource value: 0x7f050010
			public const int ratingsOptions = 2131034128;
			
			// aapt resource value: 0x7f05002b
			public const int scrollView1 = 2131034155;
			
			// aapt resource value: 0x7f050031
			public const int scrollView2 = 2131034161;
			
			// aapt resource value: 0x7f050023
			public const int scrollView3 = 2131034147;
			
			// aapt resource value: 0x7f050027
			public const int season = 2131034151;
			
			// aapt resource value: 0x7f05000f
			public const int textView1 = 2131034127;
			
			// aapt resource value: 0x7f050029
			public const int textView4 = 2131034153;
			
			// aapt resource value: 0x7f050022
			public const int textView5 = 2131034146;
			
			// aapt resource value: 0x7f05002d
			public const int textView6 = 2131034157;
			
			// aapt resource value: 0x7f050025
			public const int textView7 = 2131034149;
			
			// aapt resource value: 0x7f050002
			public const int textView_activityLabel = 2131034114;
			
			// aapt resource value: 0x7f050005
			public const int textView_amenityLabel = 2131034117;
			
			// aapt resource value: 0x7f050008
			public const int textView_difficultyLabel = 2131034120;
			
			// aapt resource value: 0x7f050000
			public const int textView_mainMenuLabel = 2131034112;
			
			// aapt resource value: 0x7f050019
			public const int textView_maxDistanceLabel = 2131034137;
			
			// aapt resource value: 0x7f050017
			public const int textView_maxDurationLabel = 2131034135;
			
			// aapt resource value: 0x7f050032
			public const int trailGallery = 2131034162;
			
			// aapt resource value: 0x7f050033
			public const int trailName = 2131034163;
			
			// aapt resource value: 0x7f050034
			public const int viewpager = 2131034164;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int SearchTrails = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ViewTrail = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int ViewTrail2 = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int ViewTrail3 = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int ViewTrail4 = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int ViewTrailBase = 2130903046;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040002
			public const int app_name = 2130968578;
			
			// aapt resource value: 0x7f040000
			public const int button_updateSearchResults = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int button_viewTrail = 2130968577;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
