#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("Columbia583.Android.Resource", IsApplication=true)]

namespace Columbia583.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::ZXing.Mobile.Resource.Id.contentFrame = global::Columbia583.Android.Resource.Id.contentFrame;
			global::ZXing.Mobile.Resource.Layout.zxingscanneractivitylayout = global::Columbia583.Android.Resource.Layout.zxingscanneractivitylayout;
			global::ZXing.Mobile.Resource.Layout.zxingscannerfragmentlayout = global::Columbia583.Android.Resource.Layout.zxingscannerfragmentlayout;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.centered = global::Columbia583.Android.Resource.Attribute.centered;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.clipPadding = global::Columbia583.Android.Resource.Attribute.clipPadding;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.fadeDelay = global::Columbia583.Android.Resource.Attribute.fadeDelay;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.fadeLength = global::Columbia583.Android.Resource.Attribute.fadeLength;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.fades = global::Columbia583.Android.Resource.Attribute.fades;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.fillColor = global::Columbia583.Android.Resource.Attribute.fillColor;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.footerColor = global::Columbia583.Android.Resource.Attribute.footerColor;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.footerIndicatorHeight = global::Columbia583.Android.Resource.Attribute.footerIndicatorHeight;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.footerIndicatorStyle = global::Columbia583.Android.Resource.Attribute.footerIndicatorStyle;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.footerIndicatorUnderlinePadding = global::Columbia583.Android.Resource.Attribute.footerIndicatorUnderlinePadding;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.footerLineHeight = global::Columbia583.Android.Resource.Attribute.footerLineHeight;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.footerPadding = global::Columbia583.Android.Resource.Attribute.footerPadding;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.gapWidth = global::Columbia583.Android.Resource.Attribute.gapWidth;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.linePosition = global::Columbia583.Android.Resource.Attribute.linePosition;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.lineWidth = global::Columbia583.Android.Resource.Attribute.lineWidth;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.pageColor = global::Columbia583.Android.Resource.Attribute.pageColor;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.radius = global::Columbia583.Android.Resource.Attribute.radius;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.selectedBold = global::Columbia583.Android.Resource.Attribute.selectedBold;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.selectedColor = global::Columbia583.Android.Resource.Attribute.selectedColor;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.snap = global::Columbia583.Android.Resource.Attribute.snap;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.strokeColor = global::Columbia583.Android.Resource.Attribute.strokeColor;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.strokeWidth = global::Columbia583.Android.Resource.Attribute.strokeWidth;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.titlePadding = global::Columbia583.Android.Resource.Attribute.titlePadding;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.topPadding = global::Columbia583.Android.Resource.Attribute.topPadding;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.unselectedColor = global::Columbia583.Android.Resource.Attribute.unselectedColor;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.vpiCirclePageIndicatorStyle = global::Columbia583.Android.Resource.Attribute.vpiCirclePageIndicatorStyle;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.vpiIconPageIndicatorStyle = global::Columbia583.Android.Resource.Attribute.vpiIconPageIndicatorStyle;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.vpiLinePageIndicatorStyle = global::Columbia583.Android.Resource.Attribute.vpiLinePageIndicatorStyle;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.vpiTabPageIndicatorStyle = global::Columbia583.Android.Resource.Attribute.vpiTabPageIndicatorStyle;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.vpiTitlePageIndicatorStyle = global::Columbia583.Android.Resource.Attribute.vpiTitlePageIndicatorStyle;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.vpiUnderlinePageIndicatorStyle = global::Columbia583.Android.Resource.Attribute.vpiUnderlinePageIndicatorStyle;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Boolean.default_circle_indicator_centered = global::Columbia583.Android.Resource.Boolean.default_circle_indicator_centered;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Boolean.default_circle_indicator_snap = global::Columbia583.Android.Resource.Boolean.default_circle_indicator_snap;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Boolean.default_line_indicator_centered = global::Columbia583.Android.Resource.Boolean.default_line_indicator_centered;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Boolean.default_title_indicator_selected_bold = global::Columbia583.Android.Resource.Boolean.default_title_indicator_selected_bold;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Boolean.default_underline_indicator_fades = global::Columbia583.Android.Resource.Boolean.default_underline_indicator_fades;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Color.default_circle_indicator_fill_color = global::Columbia583.Android.Resource.Color.default_circle_indicator_fill_color;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Color.default_circle_indicator_page_color = global::Columbia583.Android.Resource.Color.default_circle_indicator_page_color;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Color.default_circle_indicator_stroke_color = global::Columbia583.Android.Resource.Color.default_circle_indicator_stroke_color;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Color.default_line_indicator_selected_color = global::Columbia583.Android.Resource.Color.default_line_indicator_selected_color;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Color.default_line_indicator_unselected_color = global::Columbia583.Android.Resource.Color.default_line_indicator_unselected_color;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Color.default_title_indicator_footer_color = global::Columbia583.Android.Resource.Color.default_title_indicator_footer_color;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Color.default_title_indicator_selected_color = global::Columbia583.Android.Resource.Color.default_title_indicator_selected_color;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Color.default_title_indicator_text_color = global::Columbia583.Android.Resource.Color.default_title_indicator_text_color;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Color.default_underline_indicator_selected_color = global::Columbia583.Android.Resource.Color.default_underline_indicator_selected_color;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Color.vpi__background_holo_dark = global::Columbia583.Android.Resource.Color.vpi__background_holo_dark;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Color.vpi__background_holo_light = global::Columbia583.Android.Resource.Color.vpi__background_holo_light;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Color.vpi__bright_foreground_disabled_holo_dark = global::Columbia583.Android.Resource.Color.vpi__bright_foreground_disabled_holo_dark;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Color.vpi__bright_foreground_disabled_holo_light = global::Columbia583.Android.Resource.Color.vpi__bright_foreground_disabled_holo_light;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Color.vpi__bright_foreground_holo_dark = global::Columbia583.Android.Resource.Color.vpi__bright_foreground_holo_dark;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Color.vpi__bright_foreground_holo_light = global::Columbia583.Android.Resource.Color.vpi__bright_foreground_holo_light;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Color.vpi__bright_foreground_inverse_holo_dark = global::Columbia583.Android.Resource.Color.vpi__bright_foreground_inverse_holo_dark;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Color.vpi__bright_foreground_inverse_holo_light = global::Columbia583.Android.Resource.Color.vpi__bright_foreground_inverse_holo_light;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Color.vpi__dark_theme = global::Columbia583.Android.Resource.Color.vpi__dark_theme;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Color.vpi__light_theme = global::Columbia583.Android.Resource.Color.vpi__light_theme;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Dimension.default_circle_indicator_radius = global::Columbia583.Android.Resource.Dimension.default_circle_indicator_radius;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Dimension.default_circle_indicator_stroke_width = global::Columbia583.Android.Resource.Dimension.default_circle_indicator_stroke_width;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Dimension.default_line_indicator_gap_width = global::Columbia583.Android.Resource.Dimension.default_line_indicator_gap_width;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Dimension.default_line_indicator_line_width = global::Columbia583.Android.Resource.Dimension.default_line_indicator_line_width;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Dimension.default_line_indicator_stroke_width = global::Columbia583.Android.Resource.Dimension.default_line_indicator_stroke_width;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Dimension.default_title_indicator_clip_padding = global::Columbia583.Android.Resource.Dimension.default_title_indicator_clip_padding;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Dimension.default_title_indicator_footer_indicator_height = global::Columbia583.Android.Resource.Dimension.default_title_indicator_footer_indicator_height;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Dimension.default_title_indicator_footer_indicator_underline_padding = global::Columbia583.Android.Resource.Dimension.default_title_indicator_footer_indicator_underline_padding;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Dimension.default_title_indicator_footer_line_height = global::Columbia583.Android.Resource.Dimension.default_title_indicator_footer_line_height;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Dimension.default_title_indicator_footer_padding = global::Columbia583.Android.Resource.Dimension.default_title_indicator_footer_padding;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Dimension.default_title_indicator_text_size = global::Columbia583.Android.Resource.Dimension.default_title_indicator_text_size;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Dimension.default_title_indicator_title_padding = global::Columbia583.Android.Resource.Dimension.default_title_indicator_title_padding;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Dimension.default_title_indicator_top_padding = global::Columbia583.Android.Resource.Dimension.default_title_indicator_top_padding;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Drawable.vpi__tab_indicator = global::Columbia583.Android.Resource.Drawable.vpi__tab_indicator;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Drawable.vpi__tab_selected_focused_holo = global::Columbia583.Android.Resource.Drawable.vpi__tab_selected_focused_holo;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Drawable.vpi__tab_selected_holo = global::Columbia583.Android.Resource.Drawable.vpi__tab_selected_holo;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Drawable.vpi__tab_selected_pressed_holo = global::Columbia583.Android.Resource.Drawable.vpi__tab_selected_pressed_holo;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Drawable.vpi__tab_unselected_focused_holo = global::Columbia583.Android.Resource.Drawable.vpi__tab_unselected_focused_holo;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Drawable.vpi__tab_unselected_holo = global::Columbia583.Android.Resource.Drawable.vpi__tab_unselected_holo;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Drawable.vpi__tab_unselected_pressed_holo = global::Columbia583.Android.Resource.Drawable.vpi__tab_unselected_pressed_holo;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Id.bottom = global::Columbia583.Android.Resource.Id.bottom;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Id.none = global::Columbia583.Android.Resource.Id.none;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Id.top = global::Columbia583.Android.Resource.Id.top;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Id.triangle = global::Columbia583.Android.Resource.Id.triangle;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Id.underline = global::Columbia583.Android.Resource.Id.underline;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Integer.default_circle_indicator_orientation = global::Columbia583.Android.Resource.Integer.default_circle_indicator_orientation;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Integer.default_title_indicator_footer_indicator_style = global::Columbia583.Android.Resource.Integer.default_title_indicator_footer_indicator_style;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Integer.default_title_indicator_line_position = global::Columbia583.Android.Resource.Integer.default_title_indicator_line_position;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Integer.default_underline_indicator_fade_delay = global::Columbia583.Android.Resource.Integer.default_underline_indicator_fade_delay;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Integer.default_underline_indicator_fade_length = global::Columbia583.Android.Resource.Integer.default_underline_indicator_fade_length;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Style.TextAppearance_TabPageIndicator = global::Columbia583.Android.Resource.Style.TextAppearance_TabPageIndicator;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Style.Theme_PageIndicatorDefaults = global::Columbia583.Android.Resource.Style.Theme_PageIndicatorDefaults;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Style.Widget = global::Columbia583.Android.Resource.Style.Widget;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Style.Widget_IconPageIndicator = global::Columbia583.Android.Resource.Style.Widget_IconPageIndicator;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Style.Widget_TabPageIndicator = global::Columbia583.Android.Resource.Style.Widget_TabPageIndicator;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.CirclePageIndicator = global::Columbia583.Android.Resource.Styleable.CirclePageIndicator;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.CirclePageIndicator_android_background = global::Columbia583.Android.Resource.Styleable.CirclePageIndicator_android_background;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.CirclePageIndicator_android_orientation = global::Columbia583.Android.Resource.Styleable.CirclePageIndicator_android_orientation;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.CirclePageIndicator_centered = global::Columbia583.Android.Resource.Styleable.CirclePageIndicator_centered;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.CirclePageIndicator_fillColor = global::Columbia583.Android.Resource.Styleable.CirclePageIndicator_fillColor;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.CirclePageIndicator_pageColor = global::Columbia583.Android.Resource.Styleable.CirclePageIndicator_pageColor;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.CirclePageIndicator_radius = global::Columbia583.Android.Resource.Styleable.CirclePageIndicator_radius;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.CirclePageIndicator_snap = global::Columbia583.Android.Resource.Styleable.CirclePageIndicator_snap;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.CirclePageIndicator_strokeColor = global::Columbia583.Android.Resource.Styleable.CirclePageIndicator_strokeColor;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.CirclePageIndicator_strokeWidth = global::Columbia583.Android.Resource.Styleable.CirclePageIndicator_strokeWidth;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.LinePageIndicator = global::Columbia583.Android.Resource.Styleable.LinePageIndicator;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.LinePageIndicator_android_background = global::Columbia583.Android.Resource.Styleable.LinePageIndicator_android_background;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.LinePageIndicator_centered = global::Columbia583.Android.Resource.Styleable.LinePageIndicator_centered;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.LinePageIndicator_gapWidth = global::Columbia583.Android.Resource.Styleable.LinePageIndicator_gapWidth;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.LinePageIndicator_lineWidth = global::Columbia583.Android.Resource.Styleable.LinePageIndicator_lineWidth;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.LinePageIndicator_selectedColor = global::Columbia583.Android.Resource.Styleable.LinePageIndicator_selectedColor;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.LinePageIndicator_strokeWidth = global::Columbia583.Android.Resource.Styleable.LinePageIndicator_strokeWidth;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.LinePageIndicator_unselectedColor = global::Columbia583.Android.Resource.Styleable.LinePageIndicator_unselectedColor;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.TitlePageIndicator = global::Columbia583.Android.Resource.Styleable.TitlePageIndicator;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.TitlePageIndicator_android_background = global::Columbia583.Android.Resource.Styleable.TitlePageIndicator_android_background;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.TitlePageIndicator_android_textColor = global::Columbia583.Android.Resource.Styleable.TitlePageIndicator_android_textColor;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.TitlePageIndicator_android_textSize = global::Columbia583.Android.Resource.Styleable.TitlePageIndicator_android_textSize;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.TitlePageIndicator_clipPadding = global::Columbia583.Android.Resource.Styleable.TitlePageIndicator_clipPadding;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.TitlePageIndicator_footerColor = global::Columbia583.Android.Resource.Styleable.TitlePageIndicator_footerColor;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.TitlePageIndicator_footerIndicatorHeight = global::Columbia583.Android.Resource.Styleable.TitlePageIndicator_footerIndicatorHeight;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.TitlePageIndicator_footerIndicatorStyle = global::Columbia583.Android.Resource.Styleable.TitlePageIndicator_footerIndicatorStyle;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.TitlePageIndicator_footerIndicatorUnderlinePadding = global::Columbia583.Android.Resource.Styleable.TitlePageIndicator_footerIndicatorUnderlinePadding;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.TitlePageIndicator_footerLineHeight = global::Columbia583.Android.Resource.Styleable.TitlePageIndicator_footerLineHeight;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.TitlePageIndicator_footerPadding = global::Columbia583.Android.Resource.Styleable.TitlePageIndicator_footerPadding;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.TitlePageIndicator_linePosition = global::Columbia583.Android.Resource.Styleable.TitlePageIndicator_linePosition;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.TitlePageIndicator_selectedBold = global::Columbia583.Android.Resource.Styleable.TitlePageIndicator_selectedBold;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.TitlePageIndicator_selectedColor = global::Columbia583.Android.Resource.Styleable.TitlePageIndicator_selectedColor;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.TitlePageIndicator_titlePadding = global::Columbia583.Android.Resource.Styleable.TitlePageIndicator_titlePadding;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.TitlePageIndicator_topPadding = global::Columbia583.Android.Resource.Styleable.TitlePageIndicator_topPadding;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.UnderlinePageIndicator = global::Columbia583.Android.Resource.Styleable.UnderlinePageIndicator;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.UnderlinePageIndicator_android_background = global::Columbia583.Android.Resource.Styleable.UnderlinePageIndicator_android_background;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.UnderlinePageIndicator_fadeDelay = global::Columbia583.Android.Resource.Styleable.UnderlinePageIndicator_fadeDelay;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.UnderlinePageIndicator_fadeLength = global::Columbia583.Android.Resource.Styleable.UnderlinePageIndicator_fadeLength;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.UnderlinePageIndicator_fades = global::Columbia583.Android.Resource.Styleable.UnderlinePageIndicator_fades;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.UnderlinePageIndicator_selectedColor = global::Columbia583.Android.Resource.Styleable.UnderlinePageIndicator_selectedColor;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.ViewPagerIndicator = global::Columbia583.Android.Resource.Styleable.ViewPagerIndicator;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.ViewPagerIndicator_vpiCirclePageIndicatorStyle = global::Columbia583.Android.Resource.Styleable.ViewPagerIndicator_vpiCirclePageIndicatorStyle;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.ViewPagerIndicator_vpiIconPageIndicatorStyle = global::Columbia583.Android.Resource.Styleable.ViewPagerIndicator_vpiIconPageIndicatorStyle;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.ViewPagerIndicator_vpiLinePageIndicatorStyle = global::Columbia583.Android.Resource.Styleable.ViewPagerIndicator_vpiLinePageIndicatorStyle;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.ViewPagerIndicator_vpiTabPageIndicatorStyle = global::Columbia583.Android.Resource.Styleable.ViewPagerIndicator_vpiTabPageIndicatorStyle;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.ViewPagerIndicator_vpiTitlePageIndicatorStyle = global::Columbia583.Android.Resource.Styleable.ViewPagerIndicator_vpiTitlePageIndicatorStyle;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.ViewPagerIndicator_vpiUnderlinePageIndicatorStyle = global::Columbia583.Android.Resource.Styleable.ViewPagerIndicator_vpiUnderlinePageIndicatorStyle;
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f090000
			public const int activities_check_list = 2131296256;
			
			// aapt resource value: 0x7f090001
			public const int amenities_check_list = 2131296257;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010006
			public const int centered = 2130771974;
			
			// aapt resource value: 0x7f010011
			public const int clipPadding = 2130771985;
			
			// aapt resource value: 0x7f01001d
			public const int fadeDelay = 2130771997;
			
			// aapt resource value: 0x7f01001e
			public const int fadeLength = 2130771998;
			
			// aapt resource value: 0x7f01001c
			public const int fades = 2130771996;
			
			// aapt resource value: 0x7f01000a
			public const int fillColor = 2130771978;
			
			// aapt resource value: 0x7f010012
			public const int footerColor = 2130771986;
			
			// aapt resource value: 0x7f010015
			public const int footerIndicatorHeight = 2130771989;
			
			// aapt resource value: 0x7f010014
			public const int footerIndicatorStyle = 2130771988;
			
			// aapt resource value: 0x7f010016
			public const int footerIndicatorUnderlinePadding = 2130771990;
			
			// aapt resource value: 0x7f010013
			public const int footerLineHeight = 2130771987;
			
			// aapt resource value: 0x7f010017
			public const int footerPadding = 2130771991;
			
			// aapt resource value: 0x7f010010
			public const int gapWidth = 2130771984;
			
			// aapt resource value: 0x7f010018
			public const int linePosition = 2130771992;
			
			// aapt resource value: 0x7f01000f
			public const int lineWidth = 2130771983;
			
			// aapt resource value: 0x7f01000b
			public const int pageColor = 2130771979;
			
			// aapt resource value: 0x7f01000c
			public const int radius = 2130771980;
			
			// aapt resource value: 0x7f010019
			public const int selectedBold = 2130771993;
			
			// aapt resource value: 0x7f010007
			public const int selectedColor = 2130771975;
			
			// aapt resource value: 0x7f01000d
			public const int snap = 2130771981;
			
			// aapt resource value: 0x7f01000e
			public const int strokeColor = 2130771982;
			
			// aapt resource value: 0x7f010008
			public const int strokeWidth = 2130771976;
			
			// aapt resource value: 0x7f01001a
			public const int titlePadding = 2130771994;
			
			// aapt resource value: 0x7f01001b
			public const int topPadding = 2130771995;
			
			// aapt resource value: 0x7f010009
			public const int unselectedColor = 2130771977;
			
			// aapt resource value: 0x7f010000
			public const int vpiCirclePageIndicatorStyle = 2130771968;
			
			// aapt resource value: 0x7f010001
			public const int vpiIconPageIndicatorStyle = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int vpiLinePageIndicatorStyle = 2130771970;
			
			// aapt resource value: 0x7f010004
			public const int vpiTabPageIndicatorStyle = 2130771972;
			
			// aapt resource value: 0x7f010003
			public const int vpiTitlePageIndicatorStyle = 2130771971;
			
			// aapt resource value: 0x7f010005
			public const int vpiUnderlinePageIndicatorStyle = 2130771973;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Boolean
		{
			
			// aapt resource value: 0x7f050000
			public const int default_circle_indicator_centered = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int default_circle_indicator_snap = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int default_line_indicator_centered = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int default_title_indicator_selected_bold = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int default_underline_indicator_fades = 2131034116;
			
			static Boolean()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Boolean()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040008
			public const int default_circle_indicator_fill_color = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int default_circle_indicator_page_color = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int default_circle_indicator_stroke_color = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int default_line_indicator_selected_color = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public const int default_line_indicator_unselected_color = 2130968588;
			
			// aapt resource value: 0x7f04000d
			public const int default_title_indicator_footer_color = 2130968589;
			
			// aapt resource value: 0x7f04000e
			public const int default_title_indicator_selected_color = 2130968590;
			
			// aapt resource value: 0x7f04000f
			public const int default_title_indicator_text_color = 2130968591;
			
			// aapt resource value: 0x7f040010
			public const int default_underline_indicator_selected_color = 2130968592;
			
			// aapt resource value: 0x7f040000
			public const int vpi__background_holo_dark = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int vpi__background_holo_light = 2130968577;
			
			// aapt resource value: 0x7f040004
			public const int vpi__bright_foreground_disabled_holo_dark = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int vpi__bright_foreground_disabled_holo_light = 2130968581;
			
			// aapt resource value: 0x7f040002
			public const int vpi__bright_foreground_holo_dark = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int vpi__bright_foreground_holo_light = 2130968579;
			
			// aapt resource value: 0x7f040006
			public const int vpi__bright_foreground_inverse_holo_dark = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int vpi__bright_foreground_inverse_holo_light = 2130968583;
			
			// aapt resource value: 0x7f040011
			public const int vpi__dark_theme = 2130968593;
			
			// aapt resource value: 0x7f040012
			public const int vpi__light_theme = 2130968594;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f070000
			public const int default_circle_indicator_radius = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int default_circle_indicator_stroke_width = 2131165185;
			
			// aapt resource value: 0x7f070003
			public const int default_line_indicator_gap_width = 2131165187;
			
			// aapt resource value: 0x7f070002
			public const int default_line_indicator_line_width = 2131165186;
			
			// aapt resource value: 0x7f070004
			public const int default_line_indicator_stroke_width = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int default_title_indicator_clip_padding = 2131165189;
			
			// aapt resource value: 0x7f070007
			public const int default_title_indicator_footer_indicator_height = 2131165191;
			
			// aapt resource value: 0x7f070008
			public const int default_title_indicator_footer_indicator_underline_padding = 2131165192;
			
			// aapt resource value: 0x7f070006
			public const int default_title_indicator_footer_line_height = 2131165190;
			
			// aapt resource value: 0x7f070009
			public const int default_title_indicator_footer_padding = 2131165193;
			
			// aapt resource value: 0x7f07000a
			public const int default_title_indicator_text_size = 2131165194;
			
			// aapt resource value: 0x7f07000b
			public const int default_title_indicator_title_padding = 2131165195;
			
			// aapt resource value: 0x7f07000c
			public const int default_title_indicator_top_padding = 2131165196;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int biking = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int greenways_header_background = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int greenways_header_logo = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int hiking = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Icon = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int skiing = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int vpi__tab_indicator = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int vpi__tab_selected_focused_holo = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int vpi__tab_selected_holo = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int vpi__tab_selected_pressed_holo = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int vpi__tab_unselected_focused_holo = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int vpi__tab_unselected_holo = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int vpi__tab_unselected_pressed_holo = 2130837516;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0b001f
			public const int MaxdurationBar = 2131427359;
			
			// aapt resource value: 0x7f0b0023
			public const int Spinner = 2131427363;
			
			// aapt resource value: 0x7f0b005d
			public const int acitvity = 2131427421;
			
			// aapt resource value: 0x7f0b0086
			public const int activities = 2131427462;
			
			// aapt resource value: 0x7f0b0025
			public const int activitiesButton = 2131427365;
			
			// aapt resource value: 0x7f0b0018
			public const int activityButton = 2131427352;
			
			// aapt resource value: 0x7f0b0089
			public const int amenities = 2131427465;
			
			// aapt resource value: 0x7f0b005e
			public const int amenity = 2131427422;
			
			// aapt resource value: 0x7f0b0019
			public const int amenityButton = 2131427353;
			
			// aapt resource value: 0x7f0b0027
			public const int amentiesButton = 2131427367;
			
			// aapt resource value: 0x7f0b0003
			public const int bottom = 2131427331;
			
			// aapt resource value: 0x7f0b0085
			public const int btnAddToFavourites = 2131427461;
			
			// aapt resource value: 0x7f0b0043
			public const int btnComments = 2131427395;
			
			// aapt resource value: 0x7f0b0041
			public const int btnCreateTables = 2131427393;
			
			// aapt resource value: 0x7f0b004c
			public const int btnDeleteAllFromTables = 2131427404;
			
			// aapt resource value: 0x7f0b004b
			public const int btnDeleteSomeFromTables = 2131427403;
			
			// aapt resource value: 0x7f0b004d
			public const int btnDropTables = 2131427405;
			
			// aapt resource value: 0x7f0b0051
			public const int btnDynamicallyDisplayImages = 2131427409;
			
			// aapt resource value: 0x7f0b0046
			public const int btnGetActivities = 2131427398;
			
			// aapt resource value: 0x7f0b0047
			public const int btnGetAmenities = 2131427399;
			
			// aapt resource value: 0x7f0b0044
			public const int btnGetDatabaseLastUpdated = 2131427396;
			
			// aapt resource value: 0x7f0b004a
			public const int btnGetTrail = 2131427402;
			
			// aapt resource value: 0x7f0b0049
			public const int btnGetTrailsBySearchFilter = 2131427401;
			
			// aapt resource value: 0x7f0b0048
			public const int btnGetUsers = 2131427400;
			
			// aapt resource value: 0x7f0b0040
			public const int btnInitializeDatabase = 2131427392;
			
			// aapt resource value: 0x7f0b0042
			public const int btnInsertTables = 2131427394;
			
			// aapt resource value: 0x7f0b004f
			public const int btnLoadImageFromDatabase = 2131427407;
			
			// aapt resource value: 0x7f0b004e
			public const int btnLoadImageFromWeb = 2131427406;
			
			// aapt resource value: 0x7f0b0016
			public const int btnScanQrCode = 2131427350;
			
			// aapt resource value: 0x7f0b0056
			public const int btnSelectImage = 2131427414;
			
			// aapt resource value: 0x7f0b0045
			public const int btnSetDatabaseLastUpdated = 2131427397;
			
			// aapt resource value: 0x7f0b0014
			public const int btnStartRecordingTrail = 2131427348;
			
			// aapt resource value: 0x7f0b0015
			public const int btnStopRecordingTrail = 2131427349;
			
			// aapt resource value: 0x7f0b005c
			public const int btnUploadMedia = 2131427420;
			
			// aapt resource value: 0x7f0b0055
			public const int button1 = 2131427413;
			
			// aapt resource value: 0x7f0b0007
			public const int button_dataAccessTests = 2131427335;
			
			// aapt resource value: 0x7f0b0006
			public const int button_databaseTests = 2131427334;
			
			// aapt resource value: 0x7f0b0008
			public const int button_imageTests = 2131427336;
			
			// aapt resource value: 0x7f0b0010
			public const int button_login = 2131427344;
			
			// aapt resource value: 0x7f0b0011
			public const int button_logout = 2131427345;
			
			// aapt resource value: 0x7f0b0009
			public const int button_recordTrailTests = 2131427337;
			
			// aapt resource value: 0x7f0b0012
			public const int button_scanQrCode = 2131427346;
			
			// aapt resource value: 0x7f0b000d
			public const int button_searchTrails = 2131427341;
			
			// aapt resource value: 0x7f0b003a
			public const int button_updateSearchResults = 2131427386;
			
			// aapt resource value: 0x7f0b000e
			public const int button_viewFavouriteTrails = 2131427342;
			
			// aapt resource value: 0x7f0b0029
			public const int checkBox_difficulty_easiest = 2131427369;
			
			// aapt resource value: 0x7f0b002a
			public const int checkBox_difficulty_easy = 2131427370;
			
			// aapt resource value: 0x7f0b002d
			public const int checkBox_difficulty_extremelyDifficult = 2131427373;
			
			// aapt resource value: 0x7f0b002b
			public const int checkBox_difficulty_moreDifficult = 2131427371;
			
			// aapt resource value: 0x7f0b002c
			public const int checkBox_difficulty_veryDifficult = 2131427372;
			
			// aapt resource value: 0x7f0b008b
			public const int commentsLayout = 2131427467;
			
			// aapt resource value: 0x7f0b008a
			public const int commentsList = 2131427466;
			
			// aapt resource value: 0x7f0b0091
			public const int contentFrame = 2131427473;
			
			// aapt resource value: 0x7f0b007f
			public const int description = 2131427455;
			
			// aapt resource value: 0x7f0b001b
			public const int difficultyBar = 2131427355;
			
			// aapt resource value: 0x7f0b0084
			public const int difficultyRating = 2131427460;
			
			// aapt resource value: 0x7f0b001a
			public const int difficultyText = 2131427354;
			
			// aapt resource value: 0x7f0b0088
			public const int directions = 2131427464;
			
			// aapt resource value: 0x7f0b0060
			public const int distance = 2131427424;
			
			// aapt resource value: 0x7f0b0020
			public const int distanceText = 2131427360;
			
			// aapt resource value: 0x7f0b0062
			public const int duration = 2131427426;
			
			// aapt resource value: 0x7f0b001e
			public const int durationText = 2131427358;
			
			// aapt resource value: 0x7f0b0039
			public const int editText_maxDistance = 2131427385;
			
			// aapt resource value: 0x7f0b0037
			public const int editText_maxDuration = 2131427383;
			
			// aapt resource value: 0x7f0b000b
			public const int gridLayout_favouriteTrails = 2131427339;
			
			// aapt resource value: 0x7f0b003b
			public const int gridLayout_searchResults = 2131427387;
			
			// aapt resource value: 0x7f0b0050
			public const int imageTestImage = 2131427408;
			
			// aapt resource value: 0x7f0b007c
			public const int imageView1 = 2131427452;
			
			// aapt resource value: 0x7f0b000c
			public const int imageView_headerLogo = 2131427340;
			
			// aapt resource value: 0x7f0b0057
			public const int imgSelectedImage = 2131427415;
			
			// aapt resource value: 0x7f0b007b
			public const int layout1 = 2131427451;
			
			// aapt resource value: 0x7f0b0017
			public const int linearLayout1 = 2131427351;
			
			// aapt resource value: 0x7f0b0052
			public const int linearLayout_dynamicallyDisplayImages = 2131427410;
			
			// aapt resource value: 0x7f0b0083
			public const int maintenance = 2131427459;
			
			// aapt resource value: 0x7f0b0021
			public const int maxDistanceBar = 2131427361;
			
			// aapt resource value: 0x7f0b007a
			public const int mediaGallerySelectedMediaComment = 2131427450;
			
			// aapt resource value: 0x7f0b0079
			public const int mediaGallerySelectedMediaImage = 2131427449;
			
			// aapt resource value: 0x7f0b0078
			public const int mediaGallerySelectedMediaTitle = 2131427448;
			
			// aapt resource value: 0x7f0b0053
			public const int multiAutoCompleteTextView1 = 2131427411;
			
			// aapt resource value: 0x7f0b0067
			public const int multiAutoCompleteTextView2 = 2131427431;
			
			// aapt resource value: 0x7f0b0069
			public const int multiAutoCompleteTextView3 = 2131427433;
			
			// aapt resource value: 0x7f0b006b
			public const int multiAutoCompleteTextView4 = 2131427435;
			
			// aapt resource value: 0x7f0b006c
			public const int multiAutoCompleteTextView5 = 2131427436;
			
			// aapt resource value: 0x7f0b006d
			public const int multiAutoCompleteTextView6 = 2131427437;
			
			// aapt resource value: 0x7f0b006e
			public const int multiAutoCompleteTextView7 = 2131427438;
			
			// aapt resource value: 0x7f0b006f
			public const int multiAutoCompleteTextView8 = 2131427439;
			
			// aapt resource value: 0x7f0b0070
			public const int multiAutoCompleteTextView9 = 2131427440;
			
			// aapt resource value: 0x7f0b0000
			public const int none = 2131427328;
			
			// aapt resource value: 0x7f0b0080
			public const int openStatus = 2131427456;
			
			// aapt resource value: 0x7f0b0090
			public const int pageIndicator = 2131427472;
			
			// aapt resource value: 0x7f0b003d
			public const int prgSplashProgress = 2131427389;
			
			// aapt resource value: 0x7f0b0072
			public const int radioButton1 = 2131427442;
			
			// aapt resource value: 0x7f0b0073
			public const int radioButton2 = 2131427443;
			
			// aapt resource value: 0x7f0b0075
			public const int radioButton3 = 2131427445;
			
			// aapt resource value: 0x7f0b0076
			public const int radioButton4 = 2131427446;
			
			// aapt resource value: 0x7f0b0031
			public const int radioButton_rating_1 = 2131427377;
			
			// aapt resource value: 0x7f0b0032
			public const int radioButton_rating_2 = 2131427378;
			
			// aapt resource value: 0x7f0b0033
			public const int radioButton_rating_3 = 2131427379;
			
			// aapt resource value: 0x7f0b0034
			public const int radioButton_rating_4 = 2131427380;
			
			// aapt resource value: 0x7f0b0035
			public const int radioButton_rating_5 = 2131427381;
			
			// aapt resource value: 0x7f0b0030
			public const int radioGroup_ratings = 2131427376;
			
			// aapt resource value: 0x7f0b007d
			public const int rating = 2131427453;
			
			// aapt resource value: 0x7f0b001d
			public const int ratingBar = 2131427357;
			
			// aapt resource value: 0x7f0b0054
			public const int ratingBar1 = 2131427412;
			
			// aapt resource value: 0x7f0b001c
			public const int ratingText = 2131427356;
			
			// aapt resource value: 0x7f0b002f
			public const int ratingsOptions = 2131427375;
			
			// aapt resource value: 0x7f0b000a
			public const int scrollView1 = 2131427338;
			
			// aapt resource value: 0x7f0b0087
			public const int scrollView2 = 2131427463;
			
			// aapt resource value: 0x7f0b007e
			public const int scrollView3 = 2131427454;
			
			// aapt resource value: 0x7f0b0082
			public const int scrollView4 = 2131427458;
			
			// aapt resource value: 0x7f0b0081
			public const int season = 2131427457;
			
			// aapt resource value: 0x7f0b005f
			public const int seekBar1 = 2131427423;
			
			// aapt resource value: 0x7f0b0061
			public const int seekBar2 = 2131427425;
			
			// aapt resource value: 0x7f0b0063
			public const int seekBar3 = 2131427427;
			
			// aapt resource value: 0x7f0b002e
			public const int textView1 = 2131427374;
			
			// aapt resource value: 0x7f0b0074
			public const int textView10 = 2131427444;
			
			// aapt resource value: 0x7f0b0064
			public const int textView4 = 2131427428;
			
			// aapt resource value: 0x7f0b0065
			public const int textView5 = 2131427429;
			
			// aapt resource value: 0x7f0b0066
			public const int textView6 = 2131427430;
			
			// aapt resource value: 0x7f0b0068
			public const int textView7 = 2131427432;
			
			// aapt resource value: 0x7f0b006a
			public const int textView8 = 2131427434;
			
			// aapt resource value: 0x7f0b0071
			public const int textView9 = 2131427441;
			
			// aapt resource value: 0x7f0b0024
			public const int textView_activityLabel = 2131427364;
			
			// aapt resource value: 0x7f0b0026
			public const int textView_amenityLabel = 2131427366;
			
			// aapt resource value: 0x7f0b0005
			public const int textView_debugMenuLabel = 2131427333;
			
			// aapt resource value: 0x7f0b0028
			public const int textView_difficultyLabel = 2131427368;
			
			// aapt resource value: 0x7f0b0038
			public const int textView_maxDistanceLabel = 2131427384;
			
			// aapt resource value: 0x7f0b0036
			public const int textView_maxDurationLabel = 2131427382;
			
			// aapt resource value: 0x7f0b005b
			public const int textboxComment = 2131427419;
			
			// aapt resource value: 0x7f0b0059
			public const int textboxTitle = 2131427417;
			
			// aapt resource value: 0x7f0b0004
			public const int top = 2131427332;
			
			// aapt resource value: 0x7f0b008d
			public const int trailGallery = 2131427469;
			
			// aapt resource value: 0x7f0b008e
			public const int trailName = 2131427470;
			
			// aapt resource value: 0x7f0b0001
			public const int triangle = 2131427329;
			
			// aapt resource value: 0x7f0b003f
			public const int txtDataAccessTitle = 2131427391;
			
			// aapt resource value: 0x7f0b005a
			public const int txtEnterCommentLabel = 2131427418;
			
			// aapt resource value: 0x7f0b0058
			public const int txtEnterTitleLabel = 2131427416;
			
			// aapt resource value: 0x7f0b0013
			public const int txtLoggedInUsersUsername = 2131427347;
			
			// aapt resource value: 0x7f0b003e
			public const int txtSplashProgressLabel = 2131427390;
			
			// aapt resource value: 0x7f0b003c
			public const int txtSplashScreenTitle = 2131427388;
			
			// aapt resource value: 0x7f0b0002
			public const int underline = 2131427330;
			
			// aapt resource value: 0x7f0b0022
			public const int update = 2131427362;
			
			// aapt resource value: 0x7f0b0077
			public const int upload = 2131427447;
			
			// aapt resource value: 0x7f0b008c
			public const int uploadComment = 2131427468;
			
			// aapt resource value: 0x7f0b000f
			public const int uploadTrail = 2131427343;
			
			// aapt resource value: 0x7f0b008f
			public const int viewpager = 2131427471;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f060000
			public const int default_circle_indicator_orientation = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int default_title_indicator_footer_indicator_style = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int default_title_indicator_line_position = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int default_underline_indicator_fade_delay = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int default_underline_indicator_fade_length = 2131099652;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int DebugMenu = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int FavouriteTrails = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int RecordTrail = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int ScanQrCode = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int SearchTrailPage = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int SearchTrailPage2 = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int SearchTrails = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int SplashScreen = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int TestDataAccess = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int TestDatabase = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int TestImage = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int UploadComment = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int UploadMedia = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int UploadTrail = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int ViewMedia = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int ViewTrail = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int ViewTrail2 = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int ViewTrail3 = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int ViewTrail4 = 2130903059;
			
			// aapt resource value: 0x7f030014
			public const int ViewTrailBase = 2130903060;
			
			// aapt resource value: 0x7f030015
			public const int zxingscanneractivitylayout = 2130903061;
			
			// aapt resource value: 0x7f030016
			public const int zxingscannerfragmentlayout = 2130903062;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f0a0000
			public const int GreenValley = 2131361792;
			
			// aapt resource value: 0x7f0a0008
			public const int activitiesList = 2131361800;
			
			// aapt resource value: 0x7f0a0009
			public const int amenitiesList = 2131361801;
			
			// aapt resource value: 0x7f0a0004
			public const int app_name = 2131361796;
			
			// aapt resource value: 0x7f0a0002
			public const int button_updateSearchResults = 2131361794;
			
			// aapt resource value: 0x7f0a0003
			public const int button_viewTrail = 2131361795;
			
			// aapt resource value: 0x7f0a0006
			public const int negativeOption = 2131361798;
			
			// aapt resource value: 0x7f0a0005
			public const int positiveOption = 2131361797;
			
			// aapt resource value: 0x7f0a0007
			public const int submitButtonName = 2131361799;
			
			// aapt resource value: 0x7f0a0001
			public const int trail_prompt = 2131361793;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f080003
			public const int TextAppearance_TabPageIndicator = 2131230723;
			
			// aapt resource value: 0x7f080000
			public const int Theme_PageIndicatorDefaults = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int Widget = 2131230721;
			
			// aapt resource value: 0x7f080004
			public const int Widget_IconPageIndicator = 2131230724;
			
			// aapt resource value: 0x7f080002
			public const int Widget_TabPageIndicator = 2131230722;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] CirclePageIndicator = new int[]
			{
					16842948,
					16842964,
					2130771974,
					2130771976,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982};
			
			// aapt resource value: 1
			public const int CirclePageIndicator_android_background = 1;
			
			// aapt resource value: 0
			public const int CirclePageIndicator_android_orientation = 0;
			
			// aapt resource value: 2
			public const int CirclePageIndicator_centered = 2;
			
			// aapt resource value: 4
			public const int CirclePageIndicator_fillColor = 4;
			
			// aapt resource value: 5
			public const int CirclePageIndicator_pageColor = 5;
			
			// aapt resource value: 6
			public const int CirclePageIndicator_radius = 6;
			
			// aapt resource value: 7
			public const int CirclePageIndicator_snap = 7;
			
			// aapt resource value: 8
			public const int CirclePageIndicator_strokeColor = 8;
			
			// aapt resource value: 3
			public const int CirclePageIndicator_strokeWidth = 3;
			
			public static int[] LinePageIndicator = new int[]
			{
					16842964,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771983,
					2130771984};
			
			// aapt resource value: 0
			public const int LinePageIndicator_android_background = 0;
			
			// aapt resource value: 1
			public const int LinePageIndicator_centered = 1;
			
			// aapt resource value: 6
			public const int LinePageIndicator_gapWidth = 6;
			
			// aapt resource value: 5
			public const int LinePageIndicator_lineWidth = 5;
			
			// aapt resource value: 2
			public const int LinePageIndicator_selectedColor = 2;
			
			// aapt resource value: 3
			public const int LinePageIndicator_strokeWidth = 3;
			
			// aapt resource value: 4
			public const int LinePageIndicator_unselectedColor = 4;
			
			public static int[] TitlePageIndicator = new int[]
			{
					16842901,
					16842904,
					16842964,
					2130771975,
					2130771985,
					2130771986,
					2130771987,
					2130771988,
					2130771989,
					2130771990,
					2130771991,
					2130771992,
					2130771993,
					2130771994,
					2130771995};
			
			// aapt resource value: 2
			public const int TitlePageIndicator_android_background = 2;
			
			// aapt resource value: 1
			public const int TitlePageIndicator_android_textColor = 1;
			
			// aapt resource value: 0
			public const int TitlePageIndicator_android_textSize = 0;
			
			// aapt resource value: 4
			public const int TitlePageIndicator_clipPadding = 4;
			
			// aapt resource value: 5
			public const int TitlePageIndicator_footerColor = 5;
			
			// aapt resource value: 8
			public const int TitlePageIndicator_footerIndicatorHeight = 8;
			
			// aapt resource value: 7
			public const int TitlePageIndicator_footerIndicatorStyle = 7;
			
			// aapt resource value: 9
			public const int TitlePageIndicator_footerIndicatorUnderlinePadding = 9;
			
			// aapt resource value: 6
			public const int TitlePageIndicator_footerLineHeight = 6;
			
			// aapt resource value: 10
			public const int TitlePageIndicator_footerPadding = 10;
			
			// aapt resource value: 11
			public const int TitlePageIndicator_linePosition = 11;
			
			// aapt resource value: 12
			public const int TitlePageIndicator_selectedBold = 12;
			
			// aapt resource value: 3
			public const int TitlePageIndicator_selectedColor = 3;
			
			// aapt resource value: 13
			public const int TitlePageIndicator_titlePadding = 13;
			
			// aapt resource value: 14
			public const int TitlePageIndicator_topPadding = 14;
			
			public static int[] UnderlinePageIndicator = new int[]
			{
					16842964,
					2130771975,
					2130771996,
					2130771997,
					2130771998};
			
			// aapt resource value: 0
			public const int UnderlinePageIndicator_android_background = 0;
			
			// aapt resource value: 3
			public const int UnderlinePageIndicator_fadeDelay = 3;
			
			// aapt resource value: 4
			public const int UnderlinePageIndicator_fadeLength = 4;
			
			// aapt resource value: 2
			public const int UnderlinePageIndicator_fades = 2;
			
			// aapt resource value: 1
			public const int UnderlinePageIndicator_selectedColor = 1;
			
			public static int[] ViewPagerIndicator = new int[]
			{
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973};
			
			// aapt resource value: 0
			public const int ViewPagerIndicator_vpiCirclePageIndicatorStyle = 0;
			
			// aapt resource value: 1
			public const int ViewPagerIndicator_vpiIconPageIndicatorStyle = 1;
			
			// aapt resource value: 2
			public const int ViewPagerIndicator_vpiLinePageIndicatorStyle = 2;
			
			// aapt resource value: 4
			public const int ViewPagerIndicator_vpiTabPageIndicatorStyle = 4;
			
			// aapt resource value: 3
			public const int ViewPagerIndicator_vpiTitlePageIndicatorStyle = 3;
			
			// aapt resource value: 5
			public const int ViewPagerIndicator_vpiUnderlinePageIndicatorStyle = 5;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
